### ISSUE TITLE
Installation not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by shghadge** [wfxr/code-minimap#59]
Tried the following cmd on cargo 1.51.0 (43b129a20 2021-03-16) 
`$ cargo install --locked code-minimap`
```
    Updating crates.io index
  Installing code-minimap v0.6.4
   Compiling proc-macro2 v1.0.28
   Compiling libc v0.2.88
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.80
   Compiling version_check v0.9.2
   Compiling memchr v2.4.1
   Compiling unicode-segmentation v1.7.1
   Compiling autocfg v1.0.1
   Compiling bitflags v1.2.1
   Compiling rustversion v1.0.6
   Compiling hashbrown v0.11.2
   Compiling lazy_static v1.4.0
   Compiling strsim v0.10.0
   Compiling termcolor v1.1.2
   Compiling anyhow v1.0.52
   Compiling either v1.6.1
   Compiling heck v0.3.2
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.7.0
   Compiling itertools v0.10.3
   Compiling os_str_bytes v6.0.0
   Compiling quote v1.0.9
error[E0658]: the `unsafe_op_in_unsafe_fn` lint is unstable
   --> /home/gslab/.cargo/registry/src/github.com-1ecc6299db9ec823/os_str_bytes-6.0.0/src/lib.rs:159:1
    |
159 | #![forbid(unsafe_op_in_unsafe_fn)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #71668 <https://github.com/rust-lang/rust/issues/71668> for more information

error[E0658]: the `unsafe_op_in_unsafe_fn` lint is unstable
   --> /home/gslab/.cargo/registry/src/github.com-1ecc6299db9ec823/os_str_bytes-6.0.0/src/lib.rs:159:1
    |
159 | #![forbid(unsafe_op_in_unsafe_fn)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #71668 <https://github.com/rust-lang/rust/issues/71668> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `os_str_bytes`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `code-minimap v0.6.4`, intermediate artifacts can be found at `/tmp/cargo-installB0bUPX`

Caused by:
  build failed
```

**Comment by shghadge** [comment]
Updated cargo to the latest version and it worked. My bad
